parent = "core/raspios-bookworm"

recipes = [
    "core/rpi-raspios-setup",
    "core/set-hostname",
    "core/persist-root-home",
    "core/ssh",
    "core/rpi-uboot-setup"
]

[parameters."core/set-hostname"]
hostname = "rugix-tests"

[parameters."core/rugix-ctrl"]
version = "container"

[parameters."core/pkg-cleanup"]
autoremove = true
